ATT-142 Implement create new organization [WIP]
AriaHealth/wallet pull request #27
Opened 2023-01-20 02:03 UTC by altairrostam

2023-01-20 02:20 UTC, linerocks commented on src/components/layouts/sidebar/NavItems.ts
> +        text: 'Mediclinic Team',
In the near future when our user is not only Mediclinic, this team name will dynamically replaced with the other hospital name.

2023-01-20 02:20 UTC, linerocks commented on src/pages/api/hello.ts
>  // Next.js API route support: https://nextjs.org/docs/api-routes/introduction
We can remove this if not needed

2023-01-20 02:20 UTC, linerocks commented on src/pages/organizationStepTwo.tsx
> +        axios.post("http://localhost:8000/users", userData).then((response) => {
Please use the environment variable to make it configurable.

ref: https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

2023-01-20 02:20 UTC, linerocks commented on src/pages/team.tsx
> +    return <PrimaryLayout title="Mediclinic Team">{page}</PrimaryLayout>;
This team name should dynamically render the hospital name, not a hardcoded value.

2023-01-20 02:22 UTC, altairrostam commented on src/components/layouts/sidebar/NavItems.ts
> +        text: 'Mediclinic Team',
Ok, I will make all strings as variables

2023-01-20 02:25 UTC, linerocks commented on src/pages/organizationStepTwo.tsx
> +        console.log(userData)
once finsihed with the debugging, please remove the console.log

2023-01-25 09:38 UTC, kelvinndmo requested changes

2023-01-25 09:38 UTC, kelvinndmo commented on src/components/layouts/appbar/AppbarLayout.tsx
> +    marginLeft: 260,
Here i recommend you access the theme and use the space i.e

`theme.spacing(8)`

2023-01-25 09:38 UTC, kelvinndmo commented on src/components/layouts/appbar/AppbarLayout.tsx
> +    borderRadius: 8,
Same case here

2023-01-25 09:38 UTC, kelvinndmo commented on src/components/layouts/appbar/AppbarLayout.tsx
> +        height: 30,
Specify the units for height and width, i will also recommend using the theme.spacing instead of hard coding.

theme.spacing(1) -> 8px

2023-01-25 09:38 UTC, kelvinndmo commented on src/components/layouts/appbar/AppbarLayout.tsx
> +interface IAppbarLayout {}
Not necessary @altairrostam if there are no props defined

2023-01-25 09:38 UTC, kelvinndmo commented on src/components/layouts/appbar/AppbarLayout.tsx
> +                <Box sx={{ flexGrow: 1 }} />
<Box flexGrow={1} /> will still work here

2023-01-25 09:38 UTC, kelvinndmo commented on src/components/layouts/blank/BlankLayout.tsx
> +    children: any;
`children: React.ReactNode`

2023-01-25 09:38 UTC, kelvinndmo commented on src/components/layouts/container/AriaContainer.tsx
> +const AriaContainer = styled(Container)<ContainerProps>(() => ({
By default, i think the container props will be picked, no need to type the component again.

2023-02-01 09:54 UTC, closed without merging