Base Initialization
AriaHealth/wallet pull request #28
Opened 2023-01-25 09:02 UTC by altairrostam

-Configure eslint for linting
-Configure prettier for formatting
-Configure commitlint for consistent commit message
-Configure husky for pre-commit checking
-Configure storybook for UI building process
-Configure MUI5 for base UI library

2023-01-25 09:57 UTC, kelvinndmo requested changes

2023-01-25 09:57 UTC, kelvinndmo commented on src/.husky/pre-commit
> +cd ./src && npm run lint
Are we using npm or yarn @altairrostam , i will personally for yarn but we need to use one, the project has two lock files

2023-01-25 09:57 UTC, kelvinndmo commented on src/components/inputs/buttons/SampleButton.stories.tsx
> +import { SampleButton } from "./SampleButton";
Can we use relative import over absolute imports, you can configure this by edititng the tsconfig to add adding the base url as "."

2023-01-25 10:21 UTC, altairrostam commented on src/components/inputs/buttons/SampleButton.stories.tsx
> +import { SampleButton } from "./SampleButton";
Do you mean using absolute imports rather then relative import?
e.g instead of "../../components/Button" with relative import, it becomes "@components/Button" with absolute import?

2023-01-25 10:42 UTC, kelvinndmo commented on src/components/inputs/buttons/SampleButton.stories.tsx
> +import { SampleButton } from "./SampleButton";
Oh, yes the other way sorry

2023-01-26 04:06 UTC, linerocks commented on src/components/inputs/button/SampleButton.tsx
> +export const SampleButton = ({
Is this really a sample or you forgot to rename it?

2023-01-26 04:06 UTC, linerocks commented on src/pages/_document.tsx
> +    /* eslint-disable */
why do you need to disable eslint in this block of code?

2023-01-26 04:06 UTC, linerocks commented on src/pages/_document.tsx
> +                    <link
Let's add default title to the head, do you have suggestion what's the good default title? ex. Aria Dashboard or something else?

2023-01-26 04:06 UTC, linerocks commented on src/pages/api/hello.ts
>  // Next.js API route support: https://nextjs.org/docs/api-routes/introduction
Let's remove it if unused

2023-01-26 04:13 UTC, altairrostam commented on src/pages/_document.tsx
> +    /* eslint-disable */
Because on line 35, the type any is explicitly declared for the props (and it's not allowed on the linter settings). This is a one-off case for MUI integration

2023-01-26 04:15 UTC, altairrostam commented on src/components/inputs/button/SampleButton.tsx
> +export const SampleButton = ({
It is a sample at the moment. On the next PR for Login (ATT-167) and further, this will be removed

2023-01-26 04:15 UTC, altairrostam commented on src/pages/_document.tsx
> +                    <link
How about Aria Health?

2023-01-26 04:15 UTC, altairrostam commented on src/pages/api/hello.ts
>  // Next.js API route support: https://nextjs.org/docs/api-routes/introduction
Done

2023-01-26 04:16 UTC, linerocks commented on src/pages/_document.tsx
> +                    <link
That will do

2023-01-26 04:21 UTC, altairrostam commented on src/pages/_document.tsx
> +                    <link
Title will be defined at the page-level, so we should leave the _document.tsx file be.

From the docs:
Do not use `<title>` element with `<Head />` component from `next/document`. Titles should defined at the page-level using `<Head />` from `next/head` instead. See: https://nextjs.org/docs/messages/no-title-in-document-headeslint[@next/next/no-title-in-document-head](https://nextjs.org/docs/messages/no-title-in-document-head)

2023-01-31 02:42 UTC, merged