ATT-145: SuperAdmin Invites User and Assign Permissions
AriaHealth/wallet pull request #43
Opened 2023-02-20 11:18 UTC by altairrostam

2023-02-20 16:23 UTC, kelvinndmo approved these changes

2023-02-20 16:23 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/user/accounts/form/AssignOrganizations.tsx
> +import ListItemText from "@mui/material/ListItemText";
Nice

2023-02-20 16:23 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/user/accounts/form/AssignOrganizations.tsx
> +        <Paper sx={{ width: 200, height: 230, overflow: "auto" }}>
For the height width, use the useTheme hook the calculate the appropriate space: i.e

`
import {useTheme} from "@mui/material"
const theme = useTheme()

height=theme.spacing(10) -> 160px

`

2023-02-20 16:23 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/user/accounts/form/AssignOrganizations.tsx
> +            <DialogContent sx={{ p: 5, mt: 3 }}>
use mui spacing here too

2023-02-20 16:23 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/user/accounts/form/AssignPermissions.tsx
> +    fontSize: theme.spacing(2.5),
nice

2023-02-20 16:23 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/user/accounts/table.tsx
> +    color: "#100E6A",
perhaps somewhere in the theme?

2023-02-20 16:23 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/user/accounts/table.tsx
> +        console.log(data);
remove console.log here

2023-02-20 16:23 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/user/accounts/table.tsx
> +            <TableContainer component={"div"}>
I will advice we use React table for tables -> https://react-table-v7.tanstack.com/

2023-02-20 16:23 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/user/accounts/table.tsx
> +                <Table sx={{ minWidth: 650 }} aria-label="simple table">
the aria label is really not relevant here,right, based on the value given

2023-02-20 16:24 UTC, kelvinndmo requested changes
A fe things to fix here @altairrostam

2023-02-21 02:29 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/user/accounts/form/AssignOrganizations.tsx
> +        <Paper sx={{ width: 200, height: 230, overflow: "auto" }}>
fixed

2023-02-21 02:29 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/user/accounts/table.tsx
> +    color: "#100E6A",
fixed

2023-02-21 02:36 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/user/accounts/form/AssignOrganizations.tsx
> +            <DialogContent sx={{ p: 5, mt: 3 }}>
done

2023-02-21 02:41 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/user/accounts/table.tsx
> +            <TableContainer component={"div"}>
ok, will refactor table to become a reusable component too

2023-02-21 07:11 UTC, kelvinndmo approved these changes

2023-02-21 07:11 UTC, kelvinndmo commented on components/displays/table/AriaTable.tsx
> +    const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } =
Good stuff

2023-02-21 07:12 UTC, kelvinndmo commented
Looks good to me, good job @altairrostam

2023-02-21 07:40 UTC, merged