ATT-306 : Decrypt, parse and list encrypted data of virtual accounts fetched from API
AriaHealth/wallet pull request #76
Opened 2023-03-09 10:33 UTC by altairrostam

Decrypt, parse and list encrypted data of virtual accounts fetched from API(ATT-306)](https://myaria-health.atlassian.net/browse/ATT-306?atlOrigin=eyJpIjoiOGMwYmQyOTBhNWYyNDQxNzhiY2E2N2JjMTA2MjQxMjAiLCJwIjoiaiJ9)

Child issue of [ATT-171](https://myaria-health.atlassian.net/browse/ATT-171?atlOrigin=eyJpIjoiNGNlZGJjNjUyOWM2NDFhOGI3MGQ1NTFkZGIwMWEwOTkiLCJwIjoiaiJ9)

2023-03-09 10:57 UTC, wilsonangara commented on app/(protected)/dashboard/(admin)/patient/accounts/page.tsx
> +	const { activeOrganization } = dashboardState;
I think we can directly destructure it in the array, no? like `const [{ activeOrganization }] = useDashboard();`

2023-03-09 10:57 UTC, wilsonangara commented on app/(protected)/dashboard/(admin)/patient/accounts/page.tsx
> +	}, [data])
Does the decryption keys used only once here? if so, please remove the decryption keys after use

2023-03-09 10:57 UTC, wilsonangara commented on commons/service/crypto.service.ts
> +		})
shouldn't the `virutalAccount.va_secret` and `virtualAccount.owner_address` be decrypted as well here?

Note: `owner_address` will be `null` if the virtual account hasn't been claimed

2023-03-09 14:00 UTC, altairrostam commented on commons/service/crypto.service.ts
> +		})
i'm not sure about that. what do you think @linerocks ?

2023-03-09 14:03 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/patient/accounts/page.tsx
> +	const { activeOrganization } = dashboardState;
the entire codebase follows this style to destructure variables from a context's state. I will evaluate the stylings later on refactoring process

2023-03-09 14:04 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/patient/accounts/page.tsx
> +	}, [data])
nice catch. fixed

2023-03-10 04:15 UTC, linerocks commented on commons/service/crypto.service.ts
> +		})
@altairrostam @wilsonangara is correct

2023-03-10 05:52 UTC, kelvinndmo requested changes

2023-03-10 05:52 UTC, kelvinndmo commented on commons/service/crypto.service.ts
> +import { AsymmetricEncrypted, Mnemonic } from "@commons/interface";
use consistent casing , asymmetricEncrypted and mnemonic

2023-03-10 05:54 UTC, wilsonangara commented on commons/service/crypto.service.ts
> +import { AsymmetricEncrypted, Mnemonic } from "@commons/interface";
I think typescript's interface are meant to use capital letters right? which is different from normal functions?

2023-03-13 05:32 UTC, kelvinndmo commented on commons/service/crypto.service.ts
> +import { AsymmetricEncrypted, Mnemonic } from "@commons/interface";
I See, the name it I AsymmetricEncrypted, and IMnemonic to directly imply its an interface

2023-03-13 05:53 UTC, wilsonangara commented on commons/service/crypto.service.ts
> +import { AsymmetricEncrypted, Mnemonic } from "@commons/interface";
agreed

2023-03-13 08:14 UTC, altairrostam commented on commons/service/crypto.service.ts
> +import { AsymmetricEncrypted, Mnemonic } from "@commons/interface";
Since this is related to coding style, I will note this and make changes in future chore related PR

2023-03-13 08:29 UTC, altairrostam commented on commons/service/crypto.service.ts
> +		})
I've decrypted the owner_address but not the va_secret because currently there is no use for the va_secret for now

2023-03-13 10:02 UTC, wilsonangara approved these changes

2023-03-13 10:12 UTC, merged