ATT-304: Able to edit and verify uploaded data before creating virtual accounts
AriaHealth/wallet pull request #77
Opened 2023-03-12 15:01 UTC by altairrostam

Able to edit and verify uploaded data before creating virtual accounts(ATT-304)](https://myaria-health.atlassian.net/browse/ATT-304?atlOrigin=eyJpIjoiMzEwOTUwMTkzZmU2NDA5Yjg0MDIxNWM2MmExZTM1ODciLCJwIjoiaiJ9

Child issue of [ATT-171](https://myaria-health.atlassian.net/browse/ATT-171?atlOrigin=eyJpIjoiNGNlZGJjNjUyOWM2NDFhOGI3MGQ1NTFkZGIwMWEwOTkiLCJwIjoiaiJ9)

2023-03-13 05:31 UTC, kelvinndmo requested changes

2023-03-13 05:31 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/EditUploadedData/1-EditUploadedData.tsx
> +	} = useForm({
Will be good if you can type the form to avoid TS errors and warnings

2023-03-13 05:31 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/EditUploadedData/index.tsx
> +import EditUploadedData1 from "./1-EditUploadedData";
Curios about the naming here, what is the significance of the 1

2023-03-13 05:31 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/EditUploadedData/index.tsx
> +				return {
You can use filter here instead of map

2023-03-13 05:36 UTC, kelvinndmo requested changes

2023-03-13 05:36 UTC, kelvinndmo commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/EditUploadedData/1-EditUploadedData.tsx
> +										error={!!errors.name?.message}
Add helpert text props to AriaTextField to avoid TS errors

2023-03-13 08:33 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/EditUploadedData/index.tsx
> +import EditUploadedData1 from "./1-EditUploadedData";
So for the Uploading CSV file to create patient accounts, there are multiple processes involved. On each step, a modal is opened with the corresponding task. So the numbers are just to indicate the step. Tried naming the components file without numbers but it's a bit difficult to track which step I'm doing currently

2023-03-13 11:06 UTC, linerocks commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/UploadPatient/3-UploadPatient.tsx
> +import { IAriaDialogChildren } from "@components/feedback/dialog/dialog.def";
what is def file?

2023-03-13 18:48 UTC, wilsonangara approved these changes
Other than that, LGTM

2023-03-13 18:48 UTC, wilsonangara commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/EditUploadedData/1-EditUploadedData.tsx
> +export default EditUploadedData1;
nit: add end of file line

2023-03-13 18:48 UTC, wilsonangara commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/UploadPatient/helper.tsx
> +
I believe this should be `interface` rather than `type`. If I'm not mistaken, `type` is used for typing multiple types in a field rather than using it for defining an object

2023-03-13 18:48 UTC, wilsonangara commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/UploadPatient/helper.tsx
> +	}
Not sure if I understand the content of `else` block here

2023-03-13 18:48 UTC, wilsonangara commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/UploadPatient/helper.tsx
> +};
nit: add end of file line

2023-03-13 18:48 UTC, wilsonangara commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/UploadPatient/index.tsx
> +	const { handleClose } = props;
nit: maybe in the future we can have `typing` for `props` as well?

2023-03-13 18:48 UTC, wilsonangara commented on commons/slice/createVirtualAccounts.slice.tsx
> +export default createVirtualAccountsSlice.reducer;
nit: add end of file line

2023-03-13 18:48 UTC, wilsonangara commented on commons/utility/csvToJson.ts
> +	const promises = files.map((file) => {
maybe we can use typescript's generics here rather than returning `Promise<any[]>`?

2023-03-13 18:48 UTC, wilsonangara commented on commons/utility/csvToJson.ts
> +};
nit: add end of file line

2023-03-13 18:48 UTC, wilsonangara commented on commons/utility/uuid.ts
> +export const generateUuid = () => {
nit: add empty line here

2023-03-13 18:48 UTC, wilsonangara commented on commons/utility/uuid.ts
> +}
nit: add end of file line

2023-03-13 18:48 UTC, wilsonangara commented on components/feedback/dialog/AriaDialogActions.tsx
> +export default AriaDialogActions;
nit: add end of file line

2023-03-13 18:48 UTC, wilsonangara commented on components/feedback/dialog/AriaDialogContent.tsx
> +export default AriaDialogContent;
nit: add end of file line

2023-03-13 18:48 UTC, wilsonangara commented on components/feedback/dialog/AriaDialogTitle.tsx
> +import Typography from "@mui/material/Typography";
I think we can import it in a better way 🤔 

```suggestion
import { Box, DialogTitle, IconButton, Stack, SvgIcon, Typography } from "@mui/material"
```

2023-03-13 18:48 UTC, wilsonangara commented on components/feedback/dialog/AriaDialogContent.tsx
> +const AriaDialogContent: React.FC<AriaDialogContentProps> = (props) => {
nit: add new line here

2023-03-13 18:48 UTC, wilsonangara commented on components/feedback/dialog/AriaDialogTitle.tsx
> +const Title = styled(Typography)(({ theme }) => ({
nit: remove extra empty line

2023-03-13 18:48 UTC, wilsonangara commented on components/feedback/dialog/AriaDialogTitle.tsx
> +export default AriaDialogTitle
nit: add end of file line

2023-03-13 18:48 UTC, wilsonangara commented on components/inputs/fileUpload/AriaFileUploader.tsx
>  import Typography from "@mui/material/Typography";
please combine these imports as well

2023-03-13 18:48 UTC, wilsonangara commented on components/inputs/fileUpload/AriaFileUploader.tsx
> +export default AriaFileUploader;
nit: add end of file line

2023-03-14 08:11 UTC, altairrostam commented on components/inputs/fileUpload/AriaFileUploader.tsx
> +export default AriaFileUploader;
noted. will do cleanup on a separate chore PR

2023-03-14 08:11 UTC, altairrostam commented on components/inputs/fileUpload/AriaFileUploader.tsx
>  import Typography from "@mui/material/Typography";
noted. will do cleanup on a separate chore PR

2023-03-14 08:11 UTC, altairrostam commented on components/feedback/dialog/AriaDialogTitle.tsx
> +export default AriaDialogTitle
noted. will do cleanup on a separate chore PR

2023-03-14 08:11 UTC, altairrostam commented on components/feedback/dialog/AriaDialogTitle.tsx
> +const Title = styled(Typography)(({ theme }) => ({
noted. will do cleanup on a separate chore PR

2023-03-14 08:11 UTC, altairrostam commented on components/feedback/dialog/AriaDialogContent.tsx
> +const AriaDialogContent: React.FC<AriaDialogContentProps> = (props) => {
noted. will do cleanup on a separate chore PR

2023-03-14 08:12 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/UploadPatient/index.tsx
> +	const { handleClose } = props;
the typing is already in the Interface, i.e in this example, the typing from props came from IAriaDialogWrapper

2023-03-14 08:13 UTC, altairrostam commented on commons/utility/csvToJson.ts
> +	const promises = files.map((file) => {
you are right. will do cleanup on a separate chore PR

2023-03-14 08:13 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/UploadPatient/helper.tsx
> +};
noted. will do cleanup on a separate chore PR

2023-03-14 08:14 UTC, linerocks commented on components/feedback/dialog/AriaDialogTitle.tsx
> +import Typography from "@mui/material/Typography";
This is debatable, but I prefer Altair's approach. The reason is about tree-shaking -> https://www.telerik.com/blogs/tree-shaking-basics-for-react-applications

2023-03-14 08:14 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/EditUploadedData/1-EditUploadedData.tsx
> +	} = useForm({
noted. will do cleanup on a separate chore PR

2023-03-14 08:15 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/UploadPatient/3-UploadPatient.tsx
> +import { IAriaDialogChildren } from "@components/feedback/dialog/dialog.def";
it's a file containing interface and types

2023-03-14 08:15 UTC, altairrostam commented on app/(protected)/dashboard/(admin)/patient/accounts/actions/EditUploadedData/1-EditUploadedData.tsx
> +										error={!!errors.name?.message}
noted. will do cleanup on a separate chore PR

2023-03-14 08:17 UTC, merged